name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install
        run: pnpm install

      # - name: node esbuild
      #   run: node node_modules/esbuild/install.js

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
